name: Deploy to GitHub Pages

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Adjust as per your project's requirement
    
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy